version: '3.8'

services:
  backend:
    build: ./backend
    container_name: imap-proxy-backend
    ports:
      - "8000:8000"  # API
      - "1143:1143"  # Unsecured IMAP
      - "1993:1993"  # Secured IMAP
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./backend/logs:/app/logs
      - ./certs:/app/certs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/quarantine"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: imap-admin-ui
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  logs:
  certs:
